import Link from "next/link";
import { Bell, LogOut, UserRound } from "lucide-react";
import { RouteShell } from "@/app/components/route-shell";
import { createClient } from "@/lib/supabase/server";

export default async function SettingsPage() {
  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth.user) return <RouteShell title="Settings" eyebrow="Your account" description="Review preferences and account access."><section className="empty-card"><UserRound size={22} /><h2>Sign in to view settings</h2><p>Your preferences are private to your account.</p><Link href="/login" className="primary-button">Sign in</Link></section></RouteShell>;
  const [profileResult, preferenceResult] = await Promise.all([supabase.from("user_profiles").select("display_name, notification_permission").eq("user_id", auth.user.id).maybeSingle(), supabase.from("notification_preferences").select("*").eq("user_id", auth.user.id).maybeSingle()]);
  return <RouteShell title="Settings" eyebrow="Your account" description="Review preferences and account access."><main className="mx-auto w-full max-w-3xl px-5 py-8 lg:px-10"><div className="space-y-4"><section className="rounded-2xl border border-[var(--divider)] bg-white p-5"><div className="mb-4 flex items-center gap-3"><UserRound size={20} className="text-[var(--teal-700)]" /><div><h2 className="font-semibold">Account</h2><p className="muted">{profileResult.data?.display_name || "RemindMeds account"}</p></div></div><p className="text-sm text-[var(--ink-muted)]">{auth.user.email}</p><p className="mt-4 text-sm text-[var(--ink-muted)]">Account and password changes are not available in this MVP. Contact your service administrator if you need help.</p></section><section className="rounded-2xl border border-[var(--divider)] bg-white p-5"><div className="mb-3 flex items-center gap-3"><Bell size={20} className="text-[var(--teal-700)]" /><h2 className="font-semibold">Notifications</h2></div><p className="text-sm text-[var(--ink-muted)]">Permission: <strong>{profileResult.data?.notification_permission ?? "Not set"}</strong></p><p className="mt-2 text-sm text-[var(--ink-muted)]">{preferenceResult.error ? "Notification preferences are currently unavailable." : preferenceResult.data ? "Your saved notification preferences are active." : "No notification preferences have been saved yet."}</p><Link href="/" className="mt-4 inline-flex secondary-button">Review today’s reminders</Link></section><section className="rounded-2xl border border-[var(--divider)] bg-white p-5"><h2 className="font-semibold">Privacy and sign out</h2><p className="mt-2 text-sm text-[var(--ink-muted)]">Your medication data is scoped to your signed-in account. This page is read-only and does not change your preferences.</p><form action="/auth/signout" method="post" className="mt-4"><button type="submit" className="secondary-button"><LogOut size={16} /> Sign out</button></form></section>{(profileResult.error || preferenceResult.error) && <p className="alert-card" role="alert">Some settings could not be loaded. Your account remains secure.</p>}</div></main></RouteShell>;
}
